## Optical photons
/gps/particle opticalphoton
/gps/ang/type iso
/gps/energy 3 eV
/gps/position 0 0 9.9 cm

## X-ray
#/gps/particle gamma
#/gps/energy 6 MeV
#/gps/ene/type Mono
#/gps/pos/type Plane
#/gps/pos/shape Rectangle
#/gps/pos/halfx 5 mm # Need to hear from MTaylor about realistic sizes
#/gps/pos/halfy 5 mm
#/gps/pos/centre 0 11 0 cm
#/gps/direction 0 -1 0
#/gps/pos/rot1 0 0 1
#/gps/pos/rot2 1 0 0
